name: 'Hello World V2'
description: 'Greet using action from the same repository'
inputs:
  packageName: #id of input
    description: 'Application package name'
    required: true
  serviceAccountJson:
    description: 'Service account JSON file content'
    required: true
  releaseFileDir:
    description: 'Release file directory'
    required: true
  track:
    description: 'Track'
    required: false
  mappingFileDir:
    description: 'Mapping file directory'
    required: false


runs:
  using: 'node16'
  main: 'dist/index.js'
