name: 'Hello World V2'
description: 'Greet using action from the same repository'
inputs:
  packageName: #id of input
    description: 'Application package name'
    required: true
    default: 'com.example.app'
  serviceAccountJson:
    description: 'Service account JSON file content'
    required: true
    default: '{}'
  releaseFileDir:
    description: 'Release file directory'
    required: true
    default: './'
  track:
    description: 'Track'
    required: false
    default: 'internalSharing'
  mappingFileDir:
    description: 'Mapping file directory'
    required: false
    default: './'


runs:
  using: 'node16'
  main: 'dist/index.js'
