name: 'Print hello world'
run-name: ${{ github.actor }} is printing hello world
on: [push]
jobs:
  print-hello-world:
    - uses: actions/hello-world-javascript-action@main
      with:
       who-to-greet: 'Mona the Octocat'